@startuml

skinparam Linetype ortho
left to right direction

interface Target {
    requiredMethod()
}

class Adapter {
    requiredMethod()
}

class Adaptee {
    oldMethod()
}

Target <|.. Adapter : implements
Adapter --|> Adaptee : extends

@enduml