@startuml

skinparam Linetype ortho
left to right direction

class Target {
    requiredMethod()
}

class Adapter {
    adaptee
    requiredMethod()
}

class Adaptee {
    oldMethod()
}

Target <|-- Adapter : extends
Adapter ..> Adaptee : use

@enduml