@startuml

skinparam linetype ortho
top to bottom direction

package Interface {
    interface Aggregate {
        iterator()
    }
    interface Iterator {
        hasNext()
        next()
    }
}

Aggregate -right-> Iterator : create

package Object {
    class BookShelf {
        books
        last
        getBookAt()
        appendBook()
        getLength()
        iterator()
    }

    class BookShelfIterator {
        bookShelf
        index
        hasNext()
        next()
    }

    class Book {
        name
        getName()
    }
}

Aggregate <|.. BookShelf
Iterator <|.. BookShelfIterator

BookShelf <-right-o BookShelfIterator

BookShelf o--> Book

@enduml