@startuml

skinparam linetype ortho
top to bottom direction

interface Aggregate<<集合>> {
    iterator()
}
interface Iterator<<反復子>> {
    hasNext()
    next()
}

Aggregate .right.> Iterator : create

class ConcreteAggregate {
    iterator()
}

class ConcreteIterator {
    hasNext()
    next()
}

Aggregate <|-- ConcreteAggregate
Iterator <|-- ConcreteIterator
ConcreteAggregate <-left-o ConcreteIterator : create

@enduml